### ISSUE TITLE
Support for natbib citing functions

### ISSUE THREAD

**Issue by DanielAndreasen** [Focus/latexer#10]
This is an awesome package, and I really enjoy the `\cite` autocompletion. Is it possible to extend this a bit, so it also triggers when I use [natbib](https://www.ctan.org/pkg/natbib) citing functions.

These are `\citet`, `\citep`, `\citet*`, `\citep*`.

To make it a bit more complicated, this also takes optional commands in square brackets.

**Comment by Focus** [comment]
Thanks for the feedback. I will implement these in the next patch.

**Comment by Focus** [comment]
This is now fixed :)

**Comment by DanielAndreasen** [comment]
Thanks, I look forward to test it. Any idea when it will be updated in the package manager?

**Comment by Focus** [comment]
It is now updated

**Comment by DanielAndreasen** [comment]
Works perfectly (as far as I can see) :beers:
