### ISSUE TITLE
Support for multi file documents

### ISSUE THREAD

**Issue by danbim** [Focus/latexer#11]
I'm editing a larger document that is spread throughout multiple .tex files, e.g.,

```
main.tex
part_a.tex
...
part_z.tex
```

and main.tex includes part_a.tex to part_z.tex via \input and also includes the .bib file. Latexer does not find any citations when I'm working inside one of part_a.tex to part_z.tex.

Spontaneous ideas to overcome this situation:
- allow to set path to bibfile(s) in configuration of latexer
- scan all .tex files in dir for bibfile(s)
- use % !TEX directives (see e.g., http://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding). this way you could scan the current file to find the root file, that in turn includes all files to scan for bibtex files included.
- allow to disable bibfile autocompletion in the latexer configuration. there's a plugin (https://atom.io/packages/autocomplete-bibtex) specialized on bibtex-autocompletion that is obviously conflicting with latexer autocompletion features.

Also a good idea could be to separate the three different autocompletion features (reference, bibliography and environment) of latexer in individual plugins so people can choose freely between plugins that partially overlap in functionality (see last point in the list above).

**Comment by andrasbarany** [comment]
I had the same issue; as a very ugly hack I edited ~/.atom/packages/latexer/lib/cite-view.coffee and changed the following block:

```
  getCitations: ->
    cites = []
    bibRex = /\\bibliography{([^}]+)}/g
    while (match = bibRex.exec(@editor.getText()))
      if not /\.bib$/.test(match[1])
        match[1] += ".bib"
        path = FindLabels.getAbsolutePath(@editor.getPath(), match[1])
        cites = cites.concat(@getCitationsFromPath(path))
    cites
```

Removing the while-loop and replacing “match[1]” with the path to the .bib-file does the trick. The result looks as follows:

```
  getCitations: ->
    cites = []
    path = FindLabels.getAbsolutePath(@editor.getPath(), "[path-to-bibfile]")
    cites = cites.concat(@getCitationsFromPath(path))
    cites
```

It does seem to work, but this is obviously not a permanent solution.

**Comment by Focus** [comment]
Hi. This issue is resolved with balu's fix. The program now will look for a %!TEX root = root.tex  inside of the file.
