### ISSUE TITLE
Adding multiple citations

### ISSUE THREAD

**Issue by omrihar** [Focus/latexer#17]
I really like your plugin, and perhaps this is a beginner's problem and is already solved, but I often add multiple citations with one `\cite{}` command. The problem is that as soon as I add the first citation, the auto-complete window is closed.

I would suggest re-opening the window if a comma is added within a `\cite` environment. Alternatively add a command for `Ctrl-Shift-p` to reopen the citation window.

Thanks!

**Comment by Focus** [comment]
Hi. I think this issue was addressed in  4c726ce65d68728e0b48d415dbafb96b9684ce37 . It should support doing multiple citations and references by using `\cite{something,`. This is not yet in the official patch as I want to make a few more changes.

**Comment by omrihar** [comment]
Great! Thanks! Looking forward for it :-)
