### ISSUE TITLE
Invoke bibliography autocompleter after comma

### ISSUE THREAD

**Issue by gasteigerjo** [Focus/latexer#19]
I often use commas in `\cite` to do multiple citations at once, e.g. `\cite{Einstein.1912, Einstein.1923}`. Latexer only invokes the autocompletion for the first citation, all the others need to be inserted manually. Hence, it would be nice if a comma in `\cite{...}` would also invoke the bibliography autocompleter.

**Comment by Focus** [comment]
Hi, this should be fixed now: 4c726ce65d68728e0b48d415dbafb96b9684ce37
