### ISSUE TITLE
latexer does not find citations when tex directive has a space in it

### ISSUE THREAD

**Issue by yuergen** [Focus/latexer#20]
I use BibLaTeX with the biber backend to do citations. If I enter the \cite-keyword the latexer citation dialog pops up, but it is empty. I suspect that has something to do with the fact, that I do have a space after the percent sign in the tex directive: `% !TEX root = 000_main.tex`

As far as I understand the space is required for other TeX processing programs. There seem to be quite some issues with that. See http://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding and search in the text for `space`. Some of the commenters suggest a bit of flexibility in the detection of the directive, which sounds good to me.

**Comment by Focus** [comment]
Thanks for the bug report. This should be fixed now.

**Comment by yuergen** [comment]
Please excuse the late reply. Yes, the change does fix the error for me. Thank you for the fix!
