### ISSUE TITLE
latexer didn't provide list of citations

### ISSUE THREAD

**Issue by m0nhawk** [Focus/latexer#22]
`latexer` fails to find `.bib` files:

```
C:\Users\user\.atom\packages\latexer\lib\cite-view.coffee:154
Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Local\atom\app-1.0.9\paper.bib' {errno: -4058, code: "ENOENT", syscall: "open", path: "C:\Users\user\AppData\Local\atom\app-1.0.9\paper.bib", stack: (...)…}

C:\Users\user\.atom\packages\latexer\lib\cite-view.coffee:154
Error: ENOENT: no such file or directory, open 'C:\Users\user\AppData\Local\atom\app-1.0.9\library.bib' {errno: -4058, code: "ENOENT", syscall: "open", path: "C:\Users\user\AppData\Local\atom\app-1.0.9\library.bib", stack: (...)…}
```

**Comment by tthmok** [comment]
If you're on Windows then you may be having the same problem discussed here: https://github.com/Focus/latexer/issues/18

I created a pull request that may solve your issues that you can take a look at: https://github.com/Focus/latexer/pull/21

**Comment by Focus** [comment]
I merged the pull request, let me know if the problem still persists.

**Comment by m0nhawk** [comment]
This didn't work. But it seeks in the next folder now:

`C:\Users\user\AppData\Local\atom\app-1.0.11\`

**Comment by tthmok** [comment]
@m0nhawk Strange. Must be some cases that I didn't catch since the fix helped me out. Do you have a sample tex/bib that can show the issue?

**Comment by m0nhawk** [comment]
Simple LaTeX (after typing `{}` after `\cite` it fails with the error in console). I have folder added as a project folder in Atom.

```
\documentclass[a4paper]{article}

\begin{document}
\cite
\bibliography{test}
\bibliographystyle{plain}
\end{document}
```

And Bib:

```
@article {Consolini2005,
  author = {Consolini, Giuseppe and Kretzschmar, Matthieu and Lui, Anthony T. Y. and Zimbardo, Gaetano and Macek, Wieslaw M.},
  title = {On the magnetic field fluctuations during magnetospheric tail current disruption: A statistical approach},
  journal = {Journal of Geophysical Research: Space Physics},
  volume = {110},
  number = {A7},
  issn = {2156-2202},
  url = {http://dx.doi.org/10.1029/2004JA010947},
  doi = {10.1029/2004JA010947},
  pages = {n/a--n/a},
  keywords = {Magnetic storms and substorms, Field-aligned currents and current systems, Magnetotail, Stochastic processes, Scaling: spatial and temporal, magnetic substorms, tail current disruption, dipolarization processes, anomalous diffusion processes, complexity, turbulence},
  year = {2005},
  note = {A07202}
}
```

**Comment by tthmok** [comment]
@m0nhawk I just tried that out and couldn't replicate the issue. In a single folder I created a test.tex and a test.bib and your citation comes up after I add the bracket next to cite. I'm on Windows 8.1, if you're on another version that could be causing more issues.

http://i.imgur.com/1sqFQzT.png

**Comment by m0nhawk** [comment]
This is [mine](http://i.imgur.com/T08nbva.png).

I'm using Windows 10, Atom 1.0.11 and latexer 0.2.4.

**Comment by m0nhawk** [comment]
Oh, I was using the version 0.2.4 and not the up-to-date from a repository...

Now it fixed, that's for true.
