### ISSUE TITLE
It is not possible to search entries by their identifier when the \cite keyword is used.

### ISSUE THREAD

**Issue by yuergen** [Focus/latexer#26]
In the search window that opens when the \cite keyword is detected it is not possible to search for biblatex entries by their identifier. This can be helpful when the same sources are cited often just to check if the identifier is "spelled" correctly.

I tested adding "id, ID, identifier" as options in the package's settings, which does not resolve this issue.

I have no idea if other users would find this feature useful. If you are under the impression the feature is not necessary, please close the issue.

**Comment by Focus** [comment]
~~Hi, sorry for the late response. I think it would be a good idea to implement an option that allows users to search through entries by whatever field they want (and possibly combinations of them).~~

This is already implemented. The correct thing should be "key". I will add the details to the realm

**Comment by yuergen** [comment]
Thank you for your reply. I just tested using key - and it works for me, too. :)
