### ISSUE TITLE
Useless \end{}s are added in some cases

### ISSUE THREAD

**Issue by vladvelici** [Focus/latexer#3]
\documentclass{article}
\usepackage{tabularx}

\begin{document}

\begin{table}[htbp]
    \centering
    \begin{tabularx}{\textwidth}{XXX}
        \hline
        Alpha     & Beta     & Gamma     \ \hline
        0         & 2        & 4         \ \hline
        1         & 3        & 5         \ \hline
    \end{tabularx}
\end{table}
\end{document}

When editing the {XXX} part I get plenty of completely undesired \end{tabularx}, which makes editing those values simply impossible.

**Comment by Focus** [comment]
I can't seem to replicate this, see gif attached
![f15ffe040a0e251fcfc5ee57ca7113d7](https://cloud.githubusercontent.com/assets/93248/7274760/7aefc9b4-e8f7-11e4-8e50-cc79e6c776a6.gif)
