### ISSUE TITLE
Ignores \addbibresource{bibresource.bib} in main file

### ISSUE THREAD

**Issue by winnieXY** [Focus/latexer#5]
Using the newer package "biblatex" for citing, the use of \bibliiography{mybib.bib} is strongly discouraged. Instead the newer \addbibresource{mybib.bib} should be used. This command can be called several times to add multiple resources, which can then be used by \cite{} etc. 

I'm also not sure if latexer looks only in the same file for the .bib file, or also respects subdirs/subfiles wich are included into one huge project using \include{}. 

Maybe it would be the best, to make the path of the .bib files configurable via config.cson.
Please integrate that into latexer, as the completion of cites is very usefull! Thanks for you work on this!:

**Comment by Focus** [comment]
Hi, thanks for the bug report. I did not know that bib latex recommends that, I will fix this.

The software just looks inside the file you are editing for the \bibliography{mybib.bib} and then reads the file mybib.bib. Things like \bibliograpgy{../../mybib.bib} should also work fine.

There is very little integration for large projects with multiple includes at the moment. This is something I will be working on.

**Comment by winnieXY** [comment]
It would be cool, if it would be possible to make the path to the .bib file configurable via a config option in config.cson. I guess this is the easiest solution to get it running on huge projects (I'm currently writing my phd thesis).

**Comment by Focus** [comment]
Hi. Just to let you know, this is fixed now (on the git version) and will be in the next update. The program will now also look for a %!TEX root = sample.tex inside of the tex file to read them for the bibliography.
