### ISSUE TITLE
Citation assistance for parencite

### ISSUE THREAD

**Issue by werunom** [Focus/latexer#64]
Wanted to request whether citation features can be provided for `\parencite` as well. Currently the citation pop-up of Bibtex keys appear only for `\cite` and others. Since `parencite` is also often used, it will be nice if you can add this. 

Thanks!

**Comment by werunom** [comment]
I observed that even autocite is not supported. Would request you to look into this as well...

**Comment by y-marion** [comment]
@werunom This is already supported in the current master. As this version is not yet released to the atom package repository, you'll have to wait until @Focus releases a new version.
If you feel like testing out the current master, you can install it via apm on the commandline with `apm install https://github.com/Focus/latexer.git` (this is a development version, so bugs may be possible, although I haven't encountered any)

**Comment by werunom** [comment]
Nice to hear that. And thanks for letting me know :) As of now, I have fixed it locally. 

Will wait for the release. Excited to see that markdown is also supported. That would be great!

**Comment by werunom** [comment]
Any idea when the new version will be released?
