### ISSUE TITLE
very big border of popout window

### ISSUE THREAD

**Issue by X-G** [Focus/latexer#7]
![qq 20150614032435](https://cloud.githubusercontent.com/assets/6829403/8146652/2550bb58-1246-11e5-9ed5-56d00be52979.png)

When I use [Ond Dark UI](https://atom.io/packages/one-dark-ui) and after I change the UI font size, the popout window will have a very big border.

**Comment by Focus** [comment]
Hi. Is the border of the command pallet (Cmd+Shift+P) the same size? The code is using standard libraries from atom and there isn't much I can do about the UI.

**Comment by X-G** [comment]
![qq 20150616225239](https://cloud.githubusercontent.com/assets/6829403/8194210/5fe02e6c-147a-11e5-94d4-c4ef87a03782.png)
No, the command pallet (Cmd+Shift+P)  size is normal.

![qq 20150616225555](https://cloud.githubusercontent.com/assets/6829403/8194269/d9aea2dc-147a-11e5-8686-b7dbd3d9e721.png)
There is UI font size option when using [Ond Dark UI](https://atom.io/packages/one-dark-ui) 
If I use 10 as the font size, the border is normal, if I use larger font, the border will become larger.

**Comment by Focus** [comment]
Hi thanks for the report. I don't think I will ever be able to fix this. There is no way for me to control the UI, I am using atom-space-pen-views libraries to do this.
