### ISSUE TITLE
Wrong autocompletion of begin keyword

### ISSUE THREAD

**Issue by FlyingPumba** [Focus/latexer#8]
Hi ! When I type `\begin` Atom gives me the option to autocomplete, and then it completes as:

```
\\begin{env}
\end{env}
```

Note that the _begin_ keyword has an extra "\", and it should be:

```
\begin{env}
\end{env}
```

Atom version is: 0.211.0
Latexer version is: 0.2.3
OS is: Ubuntu 14.04

**Comment by Focus** [comment]
Hi. This extension does not do the autocompletion you have described. It only adds the \end{env} (which looks from your example as working correctly). This looks like an issue with autocomplete-plus.
