### ISSUE TITLE
No results when using multiple bibliography files

### ISSUE THREAD

**Issue by anasimtiaz** [Focus/latexer#9]
The \cite{} command triggers the search window but no results are seen when multiple bibliography files are included within \bibliography{}. Using one at a time works flawlessly though.

**Comment by Focus** [comment]
Thanks, I didn't know that you could do \bibliography{bib1,bib2}. I will fix this in the next patch. Currently it should work by including two separate \bibliography commands.

**Comment by Focus** [comment]
This issue is now fixed :)
